configserver:
    name: configuration-server
    status: config-server running !!!  https://github.com/FrancoNeto/kaztor-dev 

jhipster:
    security:
        authentication:
            jwt:
                secret: 15bc56e9ed2746b7805071831b5097cfd9e6db02
