configserver:
    name: configuration-server
    status: config-server running !!!  https://github.com/kaztor-dirkoo/kaztor-dev

jhipster:
    security:
        authentication:
            jwt:
                secret: 15bc56e9ed2746b7805071831b5097cfd9e6db02

# Enable /management/logfile endpoint for all apps
logging:
    file: ${java.io.tmpdir}/${spring.application.name}.log
eureka:
    client:
        service-url:
            defaultZone: http://admin:${spring.security.user.password}@jhipster-registry-0.jhipster-registry.default.svc.cluster.local:8761/eureka/,http://admin:${spring.security.user.password}@jhipster-registry-1.jhipster-registry.default.svc.cluster.local:8761/eureka/
