configserver:
    name: configuration-server
    status: config-server running !!!  https://github.com/kaztor-dirkoo/kaztor-dev

jhipster:
    security:
        authentication:
            jwt:
                base64-secret: MWYyNmVmZTQ0ODdkYWUzMjZjOTE4OGU4ZWZjMWUwMTRlZGRiZDAxYWQyZWNiYzkxN2I0YzMxNTc3YWEyOTBkMDNmNzlkNTc5NWUyNzA0YmUxYzViNTU4MjUwNzQ0ZGRjZWNiZg==

# Enable /management/logfile endpoint for all apps
logging:
    file: ${java.io.tmpdir}/${spring.application.name}.log
eureka:
    client:
        service-url:
            defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
